<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="components" nsURI="components" nsPrefix="components">
  <eClassifiers xsi:type="ecore:EClass" name="Model">
    <eStructuralFeatures xsi:type="ecore:EReference" name="client" eType="#//Client"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="server" eType="#//J2EEServer"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="database" eType="#//Database"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="webRealtion" eType="#//WebReleationship"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataRelation" eType="#//DataReleationship"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="appRelation" eType="#//AppReleationship"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="containerRelation" eType="#//ContainerReleationship"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Client">
    <eStructuralFeatures xsi:type="ecore:EReference" name="application" eType="#//ApplicationClient"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="browser" eType="#//Browser"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="os" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="J2EEServer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ejbContainer" eType="#//EJBContainer"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="webContainer" eType="#//WebContainer"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="os" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Database">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="os" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="databaseEngine" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Browser">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ApplicationClient">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="language" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WebContainer">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="serverApp" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//WebContainerElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EJBContainer">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="generalizationRelationship"
        upperBound="-1" eType="#//Generalization" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="namedElements" upperBound="-1"
        eType="#//NamedElement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="classifiers" upperBound="-1"
        eType="#//Classifier" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="relizationRelationship"
        upperBound="-1" eType="#//Realization" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="associations" upperBound="-1"
        eType="#//Association" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EJB" abstract="true" eSuperTypes="#//ClassElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="viewType" eType="#//ViewTypeKind"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EntityBean" eSuperTypes="#//EJB"/>
  <eClassifiers xsi:type="ecore:EClass" name="SessionBean" abstract="true" eSuperTypes="#//EJB"/>
  <eClassifiers xsi:type="ecore:EClass" name="MessageDrivenBean" eSuperTypes="#//EJB"/>
  <eClassifiers xsi:type="ecore:EClass" name="StatelessSessionBean" eSuperTypes="#//SessionBean"/>
  <eClassifiers xsi:type="ecore:EClass" name="StatefulSessionBean" eSuperTypes="#//SessionBean"/>
  <eClassifiers xsi:type="ecore:EClass" name="Servlet" eSuperTypes="#//WebContainerElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="JSPPage" eSuperTypes="#//WebContainerElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="ContainerReleationship">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ejbs" lowerBound="1" eType="#//EJBContainer"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="web" lowerBound="1" eType="#//WebContainer"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="protocol" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WebReleationship">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="protocol" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="browser" lowerBound="1"
        eType="#//Browser"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="webContainer" lowerBound="1"
        eType="#//WebContainer"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AppReleationship">
    <eStructuralFeatures xsi:type="ecore:EReference" name="app" lowerBound="1" eType="#//ApplicationClient"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ejbs" lowerBound="1" eType="#//EJBContainer"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="protocol" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataReleationship">
    <eStructuralFeatures xsi:type="ecore:EReference" name="server" lowerBound="1"
        eType="#//J2EEServer"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="database" lowerBound="1"
        eType="#//Database"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="protocol" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClassElement" eSuperTypes="#//ClassifierElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="superClass" upperBound="-1"
        eType="#//ClassElement"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isABstract" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Classifier" abstract="true" eSuperTypes="#//Type">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="namespace" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Operation" eSuperTypes="#//PackageableElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="parameters" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="opeartionType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Type" abstract="true" eSuperTypes="#//PackageableElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Property" eSuperTypes="#//PackageableElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//Type" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="propertyType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Association" eSuperTypes="#//Classifier">
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//ClassifierElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//ClassifierElement"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lowerBound" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="upperBound" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PackageElement" eSuperTypes="#//Classifier #//PackageableElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="packagedAssociation" upperBound="-1"
        eType="#//Association" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="packagedElement" upperBound="-1"
        eType="#//ClassifierElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Generalization">
    <eStructuralFeatures xsi:type="ecore:EReference" name="general" lowerBound="1"
        eType="#//Classifier"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="specific" lowerBound="1"
        eType="#//Classifier"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PackageableElement" abstract="true"
      eSuperTypes="#//NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="visibility" eType="#//VisibilityKind"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="VisibilityKind">
    <eLiterals name="public"/>
    <eLiterals name="private"/>
    <eLiterals name="protected"/>
    <eLiterals name="package"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="webModelRelationship">
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//WebContainerElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//WebContainerElement"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WebContainerElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InterfaceElement" eSuperTypes="#//ClassifierElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Aggregation" eSuperTypes="#//Association"/>
  <eClassifiers xsi:type="ecore:EEnum" name="ViewTypeKind">
    <eLiterals name="local"/>
    <eLiterals name="remote"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Realization">
    <eStructuralFeatures xsi:type="ecore:EReference" name="interfaceElem" lowerBound="1"
        eType="#//InterfaceElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="classElem" lowerBound="1"
        eType="#//ClassElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClassifierElement" abstract="true" eSuperTypes="#//Classifier">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedOperation" upperBound="-1"
        eType="#//Operation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedProperty" upperBound="-1"
        eType="#//Property" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
